### ISSUE TITLE
Implement Tree Style Tabs sidebar tabs 

### ISSUE THREAD

**Issue by perdakovich** [noriaku/firefox-monolite#1]
my suggestion

**Comment by noriaku** [comment]
Interesting, do you have a theme in mind that implements it? On the other hand, if you don't have any issues with the theme & startup-page I'll have to mark it complete. Thank you for your suggestion!

**Comment by perdakovich** [comment]
@noriaku 

>  a theme in mind that implements it

Yes, VerticalFox for example.
You can also google these: "tst sidebery, firefox userchrome, edge-style vertical tabs, tst-autohide"
