### ISSUE TITLE
Broken minimize, maximize and close buttons

### ISSUE THREAD

**Issue by venqoi** [noriaku/firefox-monolite#7]
![image](https://github.com/noriaku/firefox-monolite/assets/110314566/c82e3ace-4c68-418b-aed1-47bbb592a82e) as seen in the image they are stretched and it looks very weird

**Comment by venqoi** [comment]
It also appears that the address bar is not on top of the tabs like in your photo, unless that's some I need to change in the firefox settings

**Comment by noriaku** [comment]
Hey, I see.. I tested this theme on Linux (debian & arch distros) with Qtile, KDE & Gnome and it works perfect, maybe it's a problem with windows and the css config... I'll try to find the problem, thanks for share your issue :)

**Comment by venqoi** [comment]
Ah alright thank you!

**Comment by venqoi** [comment]
Just for a bump and another report, now there are two buttons and the tabs aren't under the address bar.
![image](https://github.com/noriaku/firefox-monolite/assets/110314566/2345745b-e919-443d-9cb6-9bd7c6ea27cb)
